Vagrant.configure("2") do |config|
    ## base box
    config.vm.box = "mintspecter/CentOS-Stream-8-ContainerEnv"
    config.vm.box_version = "1.0.0"

    # cockpit  
    config.vm.network "forwarded_port", guest: 9090, host: 19090, protocol: "tcp", auto_correct: true

    # code-serve
    config.vm.network "forwarded_port", guest: 7080, host: 17080, protocol: "tcp", auto_correct: true
  
    # config vm
    config.vm.provider "virtualbox" do |vm|
        vm.memory = "2048" # MB, "2048" is recommended.
        vm.cpus = "2"      # Core, "2" is recommended.
    end
end
